package org.oregami.references.model.types;

public enum ReferenceType {

//    PRESS_RELEASE, OFFICIAL_SITE, FAN_SITE, MIND_PROTOCOL
//    ,

    IN_GAME_CONTENT,
    GAME_PACKAGE_CONTENT,
    PRESS_RELEASE,
    MAGAZINE,
    BOOK,
    WEBSITE,
    EVENT,
    TELEVISION_AND_RADIO_CONTRIBUTIONS,
    GREY_LITERATURE,
    MIND_PROTOCOL
}