package org.oregami.gamingEnvironments.model.types;

public enum HardwarePlatformType {

    HOME_COMPUTERS_EUROPE_NORTHAMERICA,
    HOME_COMPUTERS_ASIA,
    CONSOLES_EUROPE_NORTHAMERICA,
    CONSOLES_NON_EUROPE_NORTHAMERICA,
    HANDHELDS_EUROPE_NORTHAMERICA,
    HANDHELDS_NON_EUROPE_NORTHAMERICA,
    MOBILE,
    NO_HARDWARE
    
}
